version: 2.1
jobs:
  build:
    machine: true

    steps:
      - checkout
      # build
      - run: |
          docker build -t kvokka/iqfeed:$CIRCLE_SHA1 -f Dockerfile . | cat # workaround progress bar weirdness
      # deploy
      - run: |
          set -x
          sh +x -c 'echo $DOCKER_PASS' | docker login -u=$DOCKER_USER --password-stdin
          docker push kvokka/iqfeed:$CIRCLE_SHA1
          ([[ "$CIRCLE_BRANCH" == "master" ]] && \
          docker tag kvokka/iqfeed:$CIRCLE_SHA1 kvokka/iqfeed:latest
          docker push kvokka/iqfeed:latest
          ) || exit 0

workflows:
  version: 2
  pipeline:
    jobs:
      - build
